<?php

namespace Database\Seeders;

use App\Models\Job;
use App\Models\User;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    /**
     * Ten open livelihood listings (two featured) plus one closed posting.
     */
    public function run(): void
    {
        $poster = User::query()->where('role', 'staff')->value('id')
            ?? User::query()->where('role', 'admin')->value('id');

        $rows = [
            [
                'title'           => 'Barangay Utility Worker (Quad Staff)',
                'company'         => 'Barangay Sigla',
                'category'        => 'general',
                'location'        => 'Barangay Hall, District II',
                'employment_type' => 'full_time',
                'salary'          => '₱600 / day',
                'description'     => 'Maintain cleanliness of the barangay hall and records room, assist in the distribution of forms, and support the weekly clean-up drive. Shift starts at 7:30 AM, Monday to Saturday.',
                'requirements'    => 'At least high school graduate; willing to work outdoors; resident of Barangay Sigla or an adjacent barangay.',
                'contact_person'  => 'Angela R. Bautista',
                'contact_number'  => '(02) 8536-1188',
                'contact_email'   => 'staff@barangay.gov',
                'deadline'        => now()->addDays(8)->toDateString(),
                'status'          => 'open',
                'is_featured'     => true,
                'posted_by'       => $poster,
                'at'              => now()->subDays(3),
            ],
            [
                'title'           => 'Construction Helper — Residential Project',
                'company'         => 'Skyrise Builders & Supply',
                'category'        => 'construction',
                'location'        => 'Project site, Quezon City',
                'employment_type' => 'temporary',
                'salary'          => '₱550 / day',
                'description'     => 'Assist masons and carpenters on a four-month residential build. Materials handling, clean-up, and site preparation for a team of twelve.',
                'requirements'    => 'Physically fit; PPE will be provided; previous site experience is an advantage but not required.',
                'contact_person'  => 'Engr. Paolo Ramirez',
                'contact_number'  => '0917 448 2210',
                'contact_email'   => 'hr@skyrisebuilders.ph',
                'deadline'        => now()->addDays(12)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(2),
            ],
            [
                'title'           => 'Canteen Cook Assistant (Morning Shift)',
                'company'         => 'Tita Nena’s Carinderia',
                'category'        => 'food_service',
                'location'        => 'Sigla Street, Zone 4',
                'employment_type' => 'part_time',
                'salary'          => '₱450 / day',
                'description'     => 'Prepare vegetables, clean ingredients and serve lunch customers from 5:30 AM to 12:30 NN, Monday to Friday.',
                'requirements'    => 'Comfortable in a busy kitchen; food hygiene orientation will be provided on the first day.',
                'contact_person'  => 'Nena Delos Reyes',
                'contact_number'  => '0995 214 7781',
                'contact_email'   => null,
                'deadline'        => now()->addDays(5)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(4),
            ],
            [
                'title'           => 'Retail Sales Associate',
                'company'         => 'Sigla Mart',
                'category'        => 'retail',
                'location'        => 'Sigla Mart, District II',
                'employment_type' => 'full_time',
                'salary'          => '₱18,000–22,000 / month',
                'description'     => 'Handle cashier duties, replenish shelves and assist shoppers in the grocery section. Two rotating shifts with rest days every week.',
                'requirements'    => 'College level or SHS graduate; basic math; willing to work on weekends at least twice a month.',
                'contact_person'  => 'Marvin Cruz',
                'contact_number'  => '0917 330 9088',
                'contact_email'   => 'careers@sigmamart.ph',
                'deadline'        => now()->addDays(15)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(5),
            ],
            [
                'title'           => 'Home Caregiver for Senior Parent',
                'company'         => 'Private Household',
                'category'        => 'healthcare',
                'location'        => 'Purok 5, Barangay Sigla',
                'employment_type' => 'contract',
                'salary'          => '₱20,000 / month',
                'description'     => 'Assist an 82-year-old with mobility, medication reminders and light meal preparation. Live-out arrangement, eight-hour shift.',
                'requirements'    => 'Caregiving NC II or at least one year of experience with elderly patients; certificate of good conduct required.',
                'contact_person'  => 'Lorna Bautista',
                'contact_number'  => '0918 774 5512',
                'contact_email'   => null,
                'deadline'        => now()->addDays(10)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(6),
            ],
            [
                'title'           => 'Farm Hand — Vegetable Plot Cooperative',
                'company'         => 'Sigla Urban Farm Cooperative',
                'category'        => 'agriculture',
                'location'        => 'City lots, District II',
                'employment_type' => 'part_time',
                'salary'          => '₱400 / day',
                'description'     => 'Prepare beds, water and harvest eggplant, okra and leafy greens for the weekly market run. Work is from 5:30 AM to 10:30 AM.',
                'requirements'    => 'Willing to work under the sun; training on organic spraying provided.',
                'contact_person'  => 'Teresita Ocampo',
                'contact_number'  => '0995 661 3390',
                'contact_email'   => 'siglafarm@gmail.com',
                'deadline'        => now()->addDays(7)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(7),
            ],
            [
                'title'           => 'Customer Service Associate (On-site)',
                'company'         => 'Northwave BPO Solutions',
                'category'        => 'bpo',
                'location'        => 'Ortigas extension, Pasig City',
                'employment_type' => 'full_time',
                'salary'          => '₱23,000–26,000 / month',
                'description'     => 'Handle chat and email support for an e-commerce account. Night shift with transportation allowance and monthly attendance bonus.',
                'requirements'    => 'At least college level; excellent written English; willing to work on site five days a week.',
                'contact_person'  => 'Kim Villamor',
                'contact_number'  => '0917 889 4471',
                'contact_email'   => 'recruit@northwavebpo.ph',
                'deadline'        => now()->addDays(9)->toDateString(),
                'status'          => 'open',
                'is_featured'     => true,
                'posted_by'       => $poster,
                'at'              => now()->subDay(),
            ],
            [
                'title'           => 'Household Helper (Live-out)',
                'company'         => 'Private Household',
                'category'        => 'domestic',
                'location'        => 'Purok 2, Barangay Sigla',
                'employment_type' => 'full_time',
                'salary'          => '₱16,000 / month',
                'description'     => 'General housekeeping for a family of four: laundry, light cooking and dishwashing, six days a week.',
                'requirements'    => 'Trustworthy and detail-oriented; references will be checked; live-out applicants preferred.',
                'contact_person'  => 'Mr. & Mrs. Garcia',
                'contact_number'  => '0918 112 6644',
                'contact_email'   => null,
                'deadline'        => now()->addDays(14)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(8),
            ],
            [
                'title'           => 'Electrician / Maintenance Technician',
                'company'         => 'Halimgawa Facilities Services',
                'category'        => 'technical',
                'location'        => 'Mandaluyong City',
                'employment_type' => 'contract',
                'salary'          => '₱700 / day',
                'description'     => 'Perform preventive maintenance, wiring repairs and panel inspections across three commercial buildings.',
                'requirements'    => 'TESDA NC II in Electrical Installation and Maintenance; at least two years of building maintenance experience.',
                'contact_person'  => 'Rico Santillan',
                'contact_number'  => '0917 220 5514',
                'contact_email'   => 'jobs@halimgawa.ph',
                'deadline'        => now()->addDays(11)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(2),
            ],
            [
                'title'           => 'Delivery Rider (Own Motorcycle)',
                'company'         => 'Sigla Express Food Delivery',
                'category'        => 'general',
                'location'        => 'Barangay Sigla and nearby barangays',
                'employment_type' => 'freelance',
                'salary'          => '₱500 / day + incentives',
                'description'     => 'Deliver food and parcel orders using the app. Choose your own hours — minimum four hours per shift, daily payout.',
                'requirements'    => 'Valid motorcycle driver’s license; smartphone; own unit with helmet and rain gear.',
                'contact_person'  => 'Jomar Panganiban',
                'contact_number'  => '0995 004 7712',
                'contact_email'   => 'ops@siglaexpress.ph',
                'deadline'        => now()->addDays(6)->toDateString(),
                'status'          => 'open',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subHours(20),
            ],
            [
                'title'           => 'Event Photographer — Barangay Fiesta',
                'company'         => 'LumiCapture Studio',
                'category'        => 'general',
                'location'        => 'Barangay Sigla',
                'employment_type' => 'freelance',
                'salary'          => '₱4,500 / event',
                'description'     => 'Cover the fiesta parade, program and night concert. Deliver 150 edited photos within three days.',
                'requirements'    => 'Portfolio required; own camera and lighting kit; must be available on the fiesta weekend.',
                'contact_person'  => 'Bea Villareal',
                'contact_number'  => '0918 550 2231',
                'contact_email'   => 'hello@lumicapture.ph',
                'deadline'        => now()->subDays(5)->toDateString(),
                'status'          => 'closed',
                'is_featured'     => false,
                'posted_by'       => $poster,
                'at'              => now()->subDays(20),
            ],
        ];

        foreach ($rows as $row) {
            $at = $row['at'];
            unset($row['at']);

            $job = Job::query()->firstOrCreate(['title' => $row['title']], $row);

            $job->forceFill(['created_at' => $at, 'updated_at' => $at])->save();
        }
    }
}
